Presentation/Areas/Admin/Models/Order/OrderIndexModel.cs
using NikanBase.Core.Enums;
using Shop.Core.Enums;
using Shop.Core.Infrastructure;
using Shop.Models.Account;

namespace Shop.Areas.Admin.Models.Order
{
    public class OrderIndexModel:BaseModel
    {
        public OrderIndexModel()
        {

        }
        public string Number { get; set; }
        public string CreatedAt { get; set; }
        public string PaidAt { get; set; }
        public decimal PayableAmount { get; set; }
        public long UserId { get; set; }
        public RegisterModel User { get; set; }
        public StatusTypes Status { get; set; }
        public string StatusName { get; set; }
        public BankGatewayTypes? Getway { get; set; }
        public ShippingSatusTypes? ShippingStatus { get; set; }
        public string GetwayName { get; set; }
        public string ShippingStatusName { get; set; }
        public string TransactionNumber { get; set; }
        public string TransactionCode { get; set; }
        public bool Payable { get; set; }
        public string UserFullName { get; set; }
        public string Mobile { get; set; }
        public void FillField()
        {
            UserFullName = User.FirstName + " " + User.LastName;
            Mobile = User.PhoneNumber;
            StatusName = Status.EnumToDescription();
            GetwayName = Getway.HasValue ? Getway.EnumToDescription() : "";
            ShippingStatusName = ShippingStatus.HasValue ? ShippingStatus.EnumToDescription() : "";
            if (Status==StatusTypes.Registered||Status==StatusTypes.UnsuccessfulPayment)
            {
                Payable = true;
            }
        }
    }
}

Presentation/Areas/Admin/Models/Order/OrderModel.cs
using System.Collections.Generic;

namespace Shop.Areas.Admin.Models.Order
{
    public class OrderModel:BaseModel
    {
        public OrderModel()
        {

        }
        public string Number { get; set; }
        public decimal PayableAmount { get; set; }
        public long UserId { get; set; }
        public string Address { get; set; }
        public ICollection<OrderItemModel> OrderItems { get; set; }
    }
}

Presentation/Areas/Admin/Controllers/OrderController.cs
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using AutoMapper;
using Kendo.Mvc.Extensions;
using Kendo.Mvc.UI;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Localization;
using Microsoft.Extensions.Logging;
using Shop.Areas.Admin.Models;
using Shop.Areas.Admin.Models.Order;
using Shop.Controllers;
using Shop.Core.Enums;
using Shop.Core.Infrastructure;
using Shop.Models.ShopCard;
using Shop.Services.Dto.Product;
using Shop.Services.Shop;
using Shop.Services.Users;

namespace Shop.Areas.Admin.Controllers
{
    [Route("api/[controller]")]
    [Route("[area]/[controller]")]
    public class OrderController : BaseAdminController
    {
        #region Fields
        private readonly IMapper _mapper;
        private readonly IOrderService _orderService;
        private readonly IAppContext _appContext;
        private readonly UserManager _userManager;
        #endregion

        #region Constructors
        public OrderController(
            IStringLocalizer<OrderIndexModel> localizer,
            IMapper mapper, IOrderService orderService,
            ILogger<OrderController> logger,
             IAppContext appContext,
              UserManager userManager
        ) : base(logger, localizer)
        {
            _mapper = mapper;
            _orderService = orderService;
            _appContext = appContext;
            _userManager = userManager;
        }

        #endregion

        #region Actions
        [HttpGet("[action]")]
        [Authorize(Roles = UserRoleNames.User)]
        public IActionResult Index()
        {
            ViewBag.Status = GetStatusTypeSelectList();
            ViewBag.Shippings = GetShippingStatusTypeSelectList();
            return View();
        }

        [HttpGet("[action]")]
        [Authorize(Roles = UserRoleNames.User)]
        public async Task<DataSourceResult> Data_Read([DataSourceRequest]DataSourceRequest request, OrderSearchModel model)
        {
            var entities = _orderService.GetAllOrderAsQueryable(_appContext.User.Id, model);
            var result = await entities.ToDataSourceResultAsync(request);
            var models = _mapper.Map<List<OrderIndexModel>>(result.Data);
            models.ForEach(x => x.FillField());
            result.Data = models;
            return result;
        }

        [HttpGet("[action]/{orderId}")]
        [Authorize(Roles = UserRoleNames.User+","+UserRoleNames.Admin)]
        public Task<ResponseState<string>> OrderDetails(long orderId)
        {
            return TryCatch(async () =>
            {
                var order = await _orderService.GetOrderById(orderId);
                var card=User.IsInRole(UserRoleNames.Admin)? await _orderService.GetCardOrder(orderId,order.UserId):
                await _orderService.GetCardOrder(orderId);
                ShippingModel model = new ShippingModel()
                {
                    Card = card,
                    OrderId = orderId
                };
                ViewBag.Number = order.Number;
                ViewBag.IsPayable = false;
                ViewBag.IsPaid = false;
                if (order.Status==StatusTypes.Registered || order.Status==StatusTypes.UnsuccessfulPayment)
                {
                    ViewBag.IsPayable = true;
                }
                if (order.Status == StatusTypes.SuccessfulPayment)
                {
                    ViewBag.IsPaid = true;
                }
                var view = await PartialViewToString(PartialView("Details", model), ControllerContext);
                return Success(data: view);
            });
        }


        [HttpGet("[action]")]
        [Authorize(Roles = UserRoleNames.Admin)]
        public IActionResult OrderIndex()
        {
            ViewBag.Status = GetStatusTypeSelectList();
            ViewBag.Shippings = GetShippingStatusTypeSelectList();
            ViewBag.Users = GetUserSelectList();
            return View();
        }

        [HttpGet("[action]")]
        [Authorize(Roles = UserRoleNames.Admin)]
        public async Task<DataSourceResult> Data_ReadOrder([DataSourceRequest]DataSourceRequest request, OrderSearchModel model)
        {
            var entities = _orderService.GetAllOrderAsQueryable(null, model);
            var result = await entities.ToDataSourceResultAsync(request);
            var models = _mapper.Map<List<OrderIndexModel>>(result.Data);
            models.ForEach(x => x.FillField());
            result.Data = models;
            return result;
        }


        [HttpPost("[action]/{id}/{state}")]
        [Authorize(Roles = UserRoleNames.Admin)]
        public Task<DefaultResponseState> ChangeStatus(long id, ShippingSatusTypes state)
        {
            return TryCatch(async () =>
            {
                if (id <= 0)
                {
                    return Error(Localizer["msg.invalid-request"].Value);
                }
                var entity = await _orderService.GetOrderById(id);
                entity.ShippingStatus = state;
                await _orderService.UpdateOrder(entity);
                return Success(message: Localizer["msg.save-succeed"].Value);
            });
        }

        #endregion

        #region Utilities
        private List<SelectListItem> GetStatusTypeSelectList()
        {
            Array values = Enum.GetValues(typeof(StatusTypes));
            List<SelectListItem> selectList = new List<SelectListItem>();
            foreach (var en in values)
            {
                selectList.Add(new SelectListItem
                {
                    Text = ((Enum)en).EnumToDescription(),
                    Value = ((byte)en).ToString()
                });

            }
            return selectList;
        }
        private List<SelectListItem> GetShippingStatusTypeSelectList()
        {
            Array values = Enum.GetValues(typeof(ShippingSatusTypes));
            List<SelectListItem> selectList = new List<SelectListItem>();
            foreach (var en in values)
            {
                selectList.Add(new SelectListItem
                {
                    Text = ((Enum)en).EnumToDescription(),
                    Value = ((byte)en).ToString()
                });

            }
            return selectList;
        }
        private List<SelectListItem> GetUserSelectList()
        {
            var users = _userManager.GetUsers().Result;
            List<SelectListItem> selectList = new List<SelectListItem>();
            foreach (var user in users)
            {
                selectList.Add(new SelectListItem
                {
                    Text = user.FullName,
                    Value = user.Id.ToString()
                });

            }
            return selectList;
        }
        #endregion
    }
}

Presentation/Controllers/ShopCardController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Logging;
using NikanBase.Core.Enums;
using Shop.Core.Enums;
using Shop.Core.Infrastructure;
using Shop.Models.ShopCard;
using Shop.Services.Dto.Product;
using Shop.Services.Shop;
using Shop.Services.Users;
using System;
using System.Collections.Generic;
using System.Text;
using System.Threading.Tasks;

namespace Shop.Controllers
{
    public class ShopCardController : BasePublicController
    {
        #region Fields
        private readonly ILogger logger;
        private readonly IMapper _mapper;
        private readonly IProductService _productService;
        private readonly ICategoryService _categoryService;
        private readonly IAppContext _appContext;
        private readonly IOrderService _orderService;
        private readonly UserManager _userManager;
        private readonly IZarinPalService _zarinPalService;
        private readonly IMellatService _mellatService;
        #endregion

        #region Constructors
        public ShopCardController(ILogger<ProductController> logger, IMapper mapper, IProductService productService
            , ICategoryService categoryService, IAppContext appContext,
            IOrderService orderService, UserManager userManager,
            IZarinPalService zarinPalService,
             IMellatService mellatService)
        {
            this.logger = logger;
            _mapper = mapper;
            _productService = productService;
            _categoryService = categoryService;
            _appContext = appContext;
            _orderService = orderService;
            _userManager = userManager;
            _zarinPalService = zarinPalService;
            _mellatService = mellatService;
        }
        #endregion

        #region Actions

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var shopCard = await _orderService.GetCard();
            ViewBag.IsFull = shopCard.IsFull;
            ViewBag.Messages = shopCard.Message;
            ViewBag.Status = shopCard.Status;
            ViewBag.FactorNumber = shopCard.FactorNumber;
            ViewBag.IsFacor = shopCard.IsFactor;
            if (Request.Headers["X-Requested-With"] == "XMLHttpRequest")
            {
                return PartialView("_Cart", shopCard.Card);
            }
            return View(shopCard.Card);
        }

        public async Task<int> ShopCardCount()
        {
            return await _orderService.GetCardCount();
        }

        [HttpGet]
        [Route("AddToCard/{id}")]
        public async Task<int> AddToCard(long id)
        {
            return await _orderService.AddToCard(id);
        }
        [HttpGet]
        [Route("AddToCard/{id}/{traitId}")]
        public async Task<int> AddToCard(long id, long traitId)
        {
            return await _orderService.AddToCard(id, traitId);
        }

        [HttpGet]
        [Route("PlusToCard/{id}")]
        public async Task<bool> PlusToCard(long id)
        {
            return await _orderService.PlusToCard(id);
        }

        [HttpGet]
        [Route("PlusToCard/{id}/{traitId}")]
        public async Task<bool> PlusToCard(long id, long traitId)
        {
            return await _orderService.PlusToCard(id, traitId);
        }

        [HttpGet]
        [Route("MinesToCard/{id}")]
        public async Task<bool> MinesToCard(long id)
        {
            return await _orderService.MinesToCard(id);
        }

        [HttpGet]
        [Route("MinesToCard/{id}/{traitId}")]
        public async Task<bool> MinesToCard(long id, int traitId)
        {
            return await _orderService.MinesToCard(id, traitId);
        }

        [HttpGet]
        [Route("RemoveFromShopCard/{id}")]
        public async Task<bool> RemoveFromShopCard(long id)
        {
            return await _orderService.RemoveFromCard(id);
        }

        [Authorize(Roles = UserRoleNames.User)]
        [HttpGet]
        [Route("shipping")]
        public async Task<IActionResult> Shipping()
        {
            List<ShopCardModel> card = new List<ShopCardModel>();
            if (HttpContext.Session.GetObjectFromJson<List<ShopCardModel>>("ShopCart") != null)
            {
                card = HttpContext.Session.GetObjectFromJson<List<ShopCardModel>>("ShopCart");
            }
            var order = await _orderService.InsertOrder(card, _appContext.User.Address);
            HttpContext.Session.SetObjectAsJson("ShopCart", order);
            return RedirectToAction("index");
        }

        [Authorize(Roles = UserRoleNames.User)]
        [HttpGet]
        public async Task<IActionResult> ConfirmOrder(string factorNumber)
        {
            var order = await _orderService.GetOrderByFactorNumber(factorNumber);
            var cardOrder = await _orderService.VerifyCard(order.Id);
            if (!cardOrder.Status)
            {
                HttpContext.Session.SetObjectAsJson("ShopCart", cardOrder.Card);
                return RedirectToAction("index");
            }
            ShippingModel model = new ShippingModel()
            {
                Address = _appContext.User.Address,
                Card = cardOrder.Card,
                OrderId = order.Id
            };
            ViewBag.Messages = cardOrder.Message;
            ViewBag.Payments = GetPaymentTypesSelectList();
            return View(model);
        }


        [Authorize(Roles = UserRoleNames.User)]
        [HttpPost]
        public async Task<IActionResult> ConfirmOrder(ShippingModel model)
        {
            var user = _appContext.User;
            user.Address = model.Address;
            var order = await _orderService.GetOrderById(model.OrderId);
            order.Address = model.Address;
            await _orderService.UpdateOrder(order);
            await _userManager.UpdateAsync(user);
            return model.PaymentTypes == PaymentTypes.ZarinPal ? RedirectToAction("Payment", new { factorNumber = order.Number })
                : RedirectToAction("MellatPayment", new { factorNumber = order.Number });
        }


        [Authorize(Roles = UserRoleNames.User)]
        [HttpGet]
        public async Task<IActionResult> Payment(string factorNumber)
        {
            var order = await _orderService.GetOrderByFactorNumber(factorNumber);

            string callbackUrl = $"{Request.Scheme}://{Request.Host}/payment/{factorNumber}";

            var result = await _zarinPalService.Payment(order.Id, callbackUrl);
            if (result.IsSuccess)
            {
                return Redirect(result.RedirectUrl);
            }
            return View(result);
        }

        [Authorize(Roles = UserRoleNames.User)]
        [HttpGet]
        public async Task<IActionResult> MellatPayment(string factorNumber)
        {
            var order = await _orderService.GetOrderByFactorNumber(factorNumber);

            string callbackUrl = $"{Request.Scheme}://{Request.Host}/mellatpay";

            var result = await _mellatService.Payment(order.Id, callbackUrl);
            if (result.IsSuccess)
            {
                return Content(RedirectToMellat(result.RefNumber));
                //return Content("<form action='https://bpm.shaparak.ir/pgwchannel/startpay.mellat' id='frmPayMellat' method='post'><input type='hidden' name='RefId' id='RefId' value='" + result.RefNumber + "' /></form><script>document.getElementById('frmPayMellat').submit();</script>");
            }
            return View(result);
        }
        #endregion

        #region Utilities
        private List<SelectListItem> GetPaymentTypesSelectList()
        {
            Array values = Enum.GetValues(typeof(PaymentTypes));
            List<SelectListItem> selectList = new List<SelectListItem>();
            foreach (var en in values)
            {
                selectList.Add(new SelectListItem
                {
                    Text = ((Enum)en).EnumToDescription(),
                    Value = ((byte)en).ToString()
                });

            }
            return selectList;
        }

        private string RedirectToMellat(string refId)
        {
            StringBuilder pgwSite = new StringBuilder();
            pgwSite.Append("<html>");
            pgwSite.AppendFormat("<body onload='document.forms[\"form\"].submit()'>");
            pgwSite.AppendFormat("<form name='form' action='{0}' method='post'>", "https://bpm.shaparak.ir/pgwchannel/startpay.mellat");
            pgwSite.AppendFormat("<input type='hidden' name='{0}' id='{1}' value='{2}' />", "RefId", "RefId", refId);
            pgwSite.Append("</form></body></html>");
            return pgwSite.ToString();
        }
        #endregion
    }
}

Presentation/Areas/Admin/Views/Order/Details.cshtml
@model Shop.Models.ShopCard.ShippingModel

@{
    int i = 1;
    string payName = ViewBag.IsPaid ? "پرداخت شده" : "قابل پرداخت";
}

<h6 class="text-center my-1">فاکتور شماره: @ViewBag.Number</h6>
<div class="container mt-2">
    <table class="table table-hover table-bordered text-center bg-white shopcardtbl">
        <tr class="bg-secondary text-white">
            <th>ردیف</th>
            <th>نام کالا</th>
            <th>مشخصه</th>
            <th>تعداد</th>
            <th>مبلغ</th>
            <th>تخفیف</th>
            <th>مبلغ اضافه شده</th>
            <th>قابل پرداخت</th>
        </tr>
        @foreach (var item in Model.Card)
        {
    <tr id="tr_@item.Product.Id">
        <td>@i</td>
        <td>  <a href="/product/@item.Product.Id/@item.Product.Name.CleanUrl()" class="text-center"> @item.Product.Name</a></td>
        <td>@item.Product.TraitText</td>
        <td>@item.Product.Count</td>
        <td>@item.Product.Price.ToString("N0")</td>
        <td>@item.Product.DiscountAmount.ToString("N0")</td>
        <td>@item.Product.PriceIncrease.ToString("N0")</td>
        <td>@(((item.Product.PriceWithDiscount + item.Product.PriceIncrease) * item.Product.Count).ToString("N0"))</td>
    </tr>
            i++;
        }
    <tr>
        <td colspan="3" class="text-center justify-content-center">جمع تعداد</td>
        <td>@Model.Card.Sum(x => x.Product.Count)</td>
        <td colspan="3">@(Model.Card.Sum(x => (x.Product.Count * (x.Product.PriceWithDiscount + x.Product.PriceIncrease))).ToString("N0")) تومان</td>
        <td>
            @if (Model.Card.Sum(x => x.Product.DiscountAmount) > 0)
            {
                <p><del>کل:@(Model.Card.Sum(x => (x.Product.Count * (x.Product.Price + x.Product.PriceIncrease))).ToString("N0")) تومان</del></p>
                <p>تخفیف: @(Model.Card.Sum(x => (x.Product.Count * x.Product.DiscountAmount)).ToString("N0")) تومان</p>
                <p>اضافه شده: @(Model.Card.Sum(x => (x.Product.Count * x.Product.PriceIncrease)).ToString("N0")) تومان</p>
                <p>
                    سود خرید: @(
                        (Model.Card.Sum(x => (x.Product.Count * (x.Product.Price + x.Product.PriceIncrease))) - Model.Card.Sum(x => (x.Product.Count * (x.Product.PriceWithDiscount + x.Product.PriceIncrease)))).ToString("N0")
                    ) تومان
                </p>
                <p>@payName: @(Model.Card.Sum(x => (x.Product.Count * (x.Product.PriceWithDiscount + x.Product.PriceIncrease))).ToString("N0")) تومان</p>
            }
            else
            {
                <p>اضافه شده: @(Model.Card.Sum(x => (x.Product.Count * x.Product.PriceIncrease)).ToString("N0")) تومان</p>
                <p>
                    سود خرید: @(
                        (Model.Card.Sum(x => (x.Product.Count * (x.Product.Price + x.Product.PriceIncrease))) - Model.Card.Sum(x => (x.Product.Count * (x.Product.PriceWithDiscount + x.Product.PriceIncrease)))).ToString("N0")
                    ) تومان
                </p>
                <p>@payName: @(Model.Card.Sum(x => (x.Product.Count * (x.Product.PriceWithDiscount + x.Product.PriceIncrease))).ToString("N0")) تومان</p>
            }
        </td>
    </tr>
    </table>
    @if (User.IsInRole(UserRoleNames.User))
    {
        @if (ViewBag.IsPayable)
        {
            <div class="row col-12 justify-content-end  mb-5 pb-5">
                <a asp-action="ConfirmOrder" asp-controller="ShopCard" asp-route-factorNumber="@Model.Card.FirstOrDefault().OrderNumber" asp-area="" class="btn btn-lg btn-danger">پرداخت</a>
            </div>
        }

    }
</div>

Presentation/Areas/Admin/Views/Order/Index.cshtml
@model Shop.Services.Dto.Product.OrderSearchModel
@{
    var OrderGridName = "OrderGrid";
    ViewBag.Title = "سفارشات من";
}
`
<div class="container text-center">
    <p class="text-center mt-3">@ViewBag.Title</p>
</div>
<hr class="k-header" />
<div class="container k-rtl">
    @(Html.Kendo().PanelBar()
              .Name("panelbar")
              .ExpandMode(PanelBarExpandMode.Multiple)
              .Items(panelbar =>
              {
                  panelbar.Add().Text("جستجو")
              .Expanded(true)
              .Content(@<form method="post" id="searchOrderForm">
                        <br />
                        <div class="row col-10">
                            <div class="col-md-2 form-group ">
                                <label asp-for="PayDate_Start" class="control-label">از تاریخ :</label>
                                @Html.EditorFor(m => m.PayDate_Start, "PersianDate")
                            </div>

                            <div class="col-md-2 form-group">
                                <label asp-for="PayDate_End" class="control-label">تا تاریخ :</label>
                                @Html.EditorFor(m => m.PayDate_End, "PersianDate")
                            </div>
                            <div class="col-md-2 form-group">
                                <label asp-for="Status" class="control-label">وضعیت سفارش :</label>
                                <select asp-for="Status" class="form-control" asp-items="@((List<SelectListItem>)ViewBag.Status)">
                                    <option selected value="">همه</option>
                                </select>
                            </div>
                            <div class="col-md-2 form-group">
                                <label asp-for="Shipping" class="control-label">وضعیت ارسال :</label>
                                <select asp-for="Shipping" class="form-control" asp-items="@((List<SelectListItem>)ViewBag.Shippings)">
                                    <option selected value="">همه</option>
                                </select>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-12">
                                <div class="form-group mt-2 ml-5 float-left">
                                    <button type="button" id="searchBtn" class="k-button"><span class="k-icon k-i-reload"></span>&nbsp;جستجو&nbsp;</button>
                                </div>
                            </div>
                        </div>
                    </form>);
}))
</div>
<br />
<div class="container-fluid k-rtl mb-5">

    @(Html.Kendo().Grid<Shop.Areas.Admin.Models.Order.OrderIndexModel>()
        .Name(OrderGridName)
        .AutoBind(true)
        .Columns(columns =>
        {
            columns.Bound(o => o.Id).Title("#").ClientTemplate("#= OrderGridIndex=IncrementRowNumber(OrderGridIndex) #").Width(45).Sortable(false).Filterable(false);
            columns.Bound(p => p.Payable)
               .ClientTemplate("#if(Payable){# " +
               "<a class='btn-sm mx-1 k-button' onclick='ShowOrders(#= data.Id #)'><span class='k-icon k-i-clock'></span>&nbsp;مشاهده</a>" +
               "<a class='k-button btn-sm m-1' href='/ShopCard/ConfirmOrder?factorNumber=#=data.Number#'><span class='k-icon k-i-check'></span>&nbsp;پرداخت</a> #}" +
               "else {# " +
               "<a class='btn-sm mx-1 k-button' onclick='ShowOrders(#= data.Id #)'><span class='k-icon k-i-clock'></span>&nbsp;مشاهده</a> #}#")
               .Title("عملیات").Width(250).HeaderHtmlAttributes(new { @class = "text-right" }).Filterable(false).Sortable(false);
            columns.Bound(p => p.Number).Title("شماره فاکتور").Width(180);
            columns.Bound(p => p.CreatedAt).Title("تاریخ ایجاد").Width(130);
            columns.Bound(p => p.ShippingStatusName).Title("وضعیت ارسال").Width(110);
            columns.Bound(p => p.StatusName).Title("وضعیت پرداخت").Width(110);
            columns.Bound(p => p.PayableAmount).Format("{0:#,0}").Title("مبلغ پرداخت").Width(110);
            columns.Bound(p => p.GetwayName).Title("درگاه").Width(120);
            columns.Bound(p => p.TransactionNumber).Title("کد پیگیری").Width(100);
            columns.Bound(p => p.TransactionCode).Title("کد مرجع").Width(100);
            columns.Bound(p => p.PaidAt).Title("تاریخ پرداخت").Width(140);

        })
        .Sortable(sortable => sortable.AllowUnsort(true).SortMode(GridSortMode.SingleColumn))
        .Pageable(pageable => pageable.Refresh(true).PageSizes(KendoGridSetting.PageSizes).Numeric(true).PreviousNext(true).Input(true).Info(true))
        .Scrollable(s => s.Height("auto"))
        //.Filterable()
        .Resizable(resize => resize.Columns(true))
        .Reorderable(reorder => reorder.Columns(true))
        .DataSource(dataSource => dataSource
            .WebApi()
            .Sort(sort => sort.Add(m => m.Id).Descending())
            .Model(model => { model.Id(p => p.Id); })
           .Read(read => read.Action("Data_Read", "Order").Data("GetSearchParameters")).PageSize(KendoGridSetting.DefaultPageSize)

        )
        .Events(events => events.DataBinding("OrderGridDataBinding"))
    )

</div>

<script>

    var OrderGridIndex = 0;

    function OrderGridDataBinding() {
        OrderGridIndex = GridDataBinding('@OrderGridName');
    }

    function ShowOrders(id) {
        OpenModal('/api/Order/OrderDetails/'+id,null, WindowNameInLayout, 'جزئیات فاکتور ','xl');
    }

    $('#searchBtn').click(function () {
        RefreshKendoGrid('@OrderGridName', '@KendoGridSetting.DefaultPageSize');
    });

    function GetSearchParameters() {
        var formdata = $('#searchOrderForm').serializeArray();
        var data = {};
        $(formdata).each(function (index, obj) {
            data[obj.name] = obj.value;
        });
         return data;
    }

</script>