Presentation/ViewComponents/BaseCardViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Shop.Areas.Admin.Models.Product;
using Shop.Services.Shop;
using Shop.Core.Infrastructure;
using Shop.Services.Dto.Setting;

namespace Shop.ViewComponents
{
    public class BaseCardViewComponent : ViewComponent
    {
        private readonly ISettingService _settingService;

        public BaseCardViewComponent(ISettingService settingService)
        {
            _settingService = settingService;

        }
        [HttpGet]
        public  IViewComponentResult Invoke(ProductShopIndexModel model)
        {
            var priceUnitSetting = _settingService.Load<PriceUnitSettingModel>(null);
            ViewBag.Unit = (priceUnitSetting != null && priceUnitSetting.Unit != 0) ? priceUnitSetting.Unit.EnumToDescription() : "ریال";
            return View(model);
        }
    }
}

Presentation/Views/Shared/Components/ProductCards/Default.cshtml
@model List<Shop.Areas.Admin.Models.Product.ProductShopIndexModel>

@if (Model.Count > 0)
{

    <div class="container my-3 site-logo mb-5">
        <div class="row product">
            @foreach (var prd in Model)
            {
            <div class="col-lg-3 col-md-3 col-sm-6 col-6 my-3 card-col">
                @await Component.InvokeAsync("BaseCard", prd)
            </div>
            }
        </div>
    </div>

}

@section Scripts{
    <script>
        //function viewProduct(id, name) {
        //    window.location.href = '/product/' + id + '/' + name;
        //}
    </script>
}