Presentation/Areas/Admin/Controllers/HomeController.cs
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Localization;
using Microsoft.Extensions.Logging;
using Shop.Controllers;
using Shop.Core.Domain.Users;
using Shop.Core.Enums;
using Shop.Core.Infrastructure;
using Shop.Services.Shop;
namespace Shop.Areas.Admin.Controllers
{
    [Authorize(Roles = UserRoleNames.Admin + "," + UserRoleNames.User)]
    public class HomeController : BaseAdminController
    {
        #region Fields

        private readonly IMessageService _messageService;
        private readonly IMapper _mapper;
        private readonly IAppContext _appContext;
        private readonly SignInManager<User> _signInManager;

        #endregion

        #region Constructors

        public HomeController(
            IStringLocalizer<HomeController> localizer,
            IMapper mapper,
            ILogger<HomeController> logger,
            IAppContext appContext,
            IMessageService messageService,
            SignInManager<User> signInManager
        ) : base(logger, localizer)
        {
            _mapper = mapper;
            _appContext = appContext;
            _messageService = messageService;
            _signInManager = signInManager;
        }


        #endregion

        #region Actions

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            await SetViewBag();
            return View();
        }

        [HttpGet("logout")]
        public async Task<IActionResult> LogOut()
        {
            await HttpContext.SignOutAsync(IdentityConstants.ApplicationScheme);
            return LocalRedirect("/");
        }

        #endregion

        #region Utilities
        private async Task SetViewBag()
        {
            var messagemodel = await _messageService.GetAllMessages();
            ViewBag.Messages = messagemodel.Where(x => x.IsRead == false).Count();
        }
        #endregion
    }
}

Presentation/Controllers/HomeController.cs
using System;
using System.IO;
using System.Text.RegularExpressions;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Diagnostics;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Shop.Core.Domain.Shop;
using Shop.Core.Infrastructure;
using Shop.Models.Message;
using Shop.Services.Dto.Getway;
using Shop.Services.Dto.Setting;
using Shop.Services.Shop;

namespace Shop.Controllers
{
    public class HomeController : BasePublicController
    {
        #region Fields
        private readonly ILogger logger;
        private readonly IMapper _mapper;
        private readonly IAppContext _appContext;
        private readonly IMessageService _messageService;
        private readonly IHostingEnvironment _environment;
        private readonly ISettingService _settingService;
        private readonly IOrderService _orderService;
        private readonly IZarinPalService _zarinPalService;
        private readonly IMellatService _mellatService;
        #endregion

        #region Constructors
        public HomeController(ILogger<HomeController> logger, IMapper mapper, IHostingEnvironment environment,
          IAppContext appContext, IMessageService messageService,
          ISettingService settingService, IOrderService orderService,
          IZarinPalService zarinPalService, IMellatService mellatService)
        {
            this.logger = logger;
            _mapper = mapper;
            _appContext = appContext;
            _messageService = messageService;
            _environment = environment;
            _settingService = settingService;
            _orderService = orderService;
            _zarinPalService = zarinPalService;
            _mellatService = mellatService;
        }
        #endregion

        #region Actions

        [HttpGet]
        public async Task<IActionResult> Index()
        {
           
            return View();
        }

        [HttpGet]
        public IActionResult Error(int? id)
        {
            var logBuilder = new System.Text.StringBuilder();

            var statusCodeReExecuteFeature = HttpContext.Features.Get<IStatusCodeReExecuteFeature>();
            logBuilder.AppendLine($"Error {id} for {Request.Method} {statusCodeReExecuteFeature?.OriginalPath ?? Request.Path.Value}{Request.QueryString.Value}\n");

            var exceptionHandlerFeature = this.HttpContext.Features.Get<IExceptionHandlerFeature>();
            if (exceptionHandlerFeature?.Error != null)
            {
                var exception = exceptionHandlerFeature.Error;
                logBuilder.AppendLine($"<h1>Exception: {exception.Message}</h1>{exception.StackTrace}");
            }

            foreach (var header in Request.Headers)
            {
                var headerValues = string.Join(",", value: header.Value);
                logBuilder.AppendLine($"{header.Key}: {headerValues}");
            }
            logger.LogError(logBuilder.ToString());

            if (id == null)
            {
                return View("Error");
            }

            switch (id.Value)
            {
                case 401:
                case 403:
                    return View("AccessDenied");
                case 404:
                    return View("NotFound");

                default:
                    return View("Error");
            }
        }

        [Route("about-us")]
        [HttpGet]
        public IActionResult About()
        {
            var setting = _settingService.Load<WebsiteSettingModel>(null);

            return View(setting);
        }

        [Route("contact-us")]
        [HttpGet]
        public async Task<IActionResult> ContactUs()
        {
            ViewBag.success = TempData["success"];
            ViewBag.error = TempData["error"];
            var setting = _settingService.Load<WebsiteSettingModel>(null);
            if (setting!=null)
            {
                ViewBag.ShopAddress = setting.ShopAddress;
                ViewBag.Phones = setting.ShopPhones;
            }
            else
            {
                ViewBag.ShopAddress = "";
                ViewBag.Phones = "";
            }
            var model = new MessageModel() { };
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Route("contact-us")]
        public async Task<IActionResult> ContactUs(MessageModel model)
        {
            if (ModelState.IsValid)
            {
                var entity = _mapper.Map<Message>(model);
                entity.IsArchived = false;
                entity.IsRead = false;
                entity.SentDate = DateTime.Now;
                await _messageService.InsertMessage(entity);
                TempData["success"] = "پیام شما با موفقیت ارسال گردید";
                return LocalRedirect("/contact-us");
            }

            TempData["error"] = "ارسال پیام با شکست مواجه گردید";
            return LocalRedirect("/contact-us");
        }



        [HttpPost]
        [Route("file-upload")]
        public async Task<IActionResult> UploadImage(IFormFile upload, string CKEditorFuncNum, string CKEditor, string langCode)
        {
            if (upload.Length <= 0) return null;

            var fileName = Guid.NewGuid() + Path.GetExtension(upload.FileName).ToLower();
            var path = Path.Combine(_environment.WebRootPath, "ckEditorImages");
            if (!Directory.Exists(path))
            {
                Directory.CreateDirectory(path);
            }
            var filePath = Path.Combine(path, fileName);
            using (var fileStream = new FileStream(filePath, FileMode.Create))
            {
                await upload.CopyToAsync(fileStream).ConfigureAwait(false);
            }
            var url = $"{"/ckEditorImages/"}{fileName}";
            return Json(new { uploaded = true, url });
        }


        [Route("payment/{factorNumber}")]
        [HttpGet]
        public async Task<IActionResult> OnlinePayment(string factorNumber)
        {
            try
            {
                string status = HttpContext.Request.Query["Status"].ToString();
                string authority = HttpContext.Request.Query["Authority"].ToString();
                var result = await _zarinPalService.VerifyPayment(factorNumber, status, authority);
                return View(result);
            }
            catch (Exception ex)
            {
                logger.LogError(ex.Message);
                return View(new ZarinPalResult() { IsSuccess = false, Message = ex.Message, StatusCode = 0, TransactionNumber = "" });
            }

        }


        [Route("mellatpay")]
        [HttpPost]
        public async Task<IActionResult> MellatPayment(/*string RefId, string ResCode, string SaleOrderId, string SaleRefrenceId*/)
        {
            string refId = HttpContext.Request.Query["RefId"].ToString();
            string resCode = HttpContext.Request.Query["ResCode"].ToString();
            string saleOrderId = HttpContext.Request.Query["SaleOrderId"].ToString();
            string saleReferenceId = HttpContext.Request.Query["SaleReferenceId"].ToString();
            var result = await _mellatService.VerifyPayment(refId, resCode, saleOrderId, saleReferenceId);
            return View(result);
        }
        #endregion
    }
}

Presentation/ViewComponents/BrandsViewComponent.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Shop.Services.Shop;
using System.Collections.Generic;
using System.Linq;
using Shop.Services.Dto.Brand;

namespace Shop.ViewComponents
{
    public class BrandsViewComponent : ViewComponent
    {
        private readonly IBrandService _brandService;
        private readonly IMapper _mapper;

        public BrandsViewComponent(IBrandService brandService, IMapper mapper)
        {
            _brandService = brandService;
            _mapper = mapper;
        }
        [HttpGet]
        public  IViewComponentResult Invoke()
        {
            var entity = _brandService.GetAllAsQueryable().ToList();
            var model = _mapper.Map<List<BrandModel>>(entity);
            return View(model);
        }
    }
}

Presentation/ViewComponents/CarouselViewComponent.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Shop.Areas.Admin.Models.Gallery;
using Shop.Services.Dto.Slider;
using Shop.Services.Shop;
using System.Collections.Generic;
using System.Linq;

namespace Shop.ViewComponents
{
    public class CarouselViewComponent:ViewComponent
    {
        private readonly IGalleryService _galleryService;
        private readonly ISliderService _sliderService;
        private readonly IMapper _mapper;

        public CarouselViewComponent(IGalleryService galleryService,
            ISliderService sliderService,
            IMapper mapper)
        {
            _galleryService = galleryService;
            _sliderService = sliderService;
            _mapper = mapper;
        }
        [HttpGet]
        public  IViewComponentResult Invoke()
        {
            var entity = _galleryService.GetAllGalleries().ToList();
            var slider = _sliderService.GetSliderByType(Core.Enums.SliderTypes.TwoSlideUp).ToList();
            var sliderModel = _mapper.Map<List<SliderModel>>(slider);
            ViewBag.Slider = sliderModel;
            var model = _mapper.Map<List<GalleryModel>>(entity);
            return View(model);
        }
    }
}

Presentation/ViewComponents/LeylounIndexViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace Shop.ViewComponents
{
    public class LeylounIndexViewComponent : ViewComponent
    {

        public LeylounIndexViewComponent()
        {
        }
        [HttpGet]
        public  IViewComponentResult Invoke()
        {
            return View();
        }
    }
}

Presentation/ViewComponents/SliderAdvViewComponent.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Shop.Services.Dto.Slider;
using Shop.Services.Shop;
using System.Linq;

namespace Shop.ViewComponents
{
    public class SliderAdvViewComponent : ViewComponent
    {
        private readonly ISliderService _sliderService;
        private readonly IMapper _mapper;

        public SliderAdvViewComponent(ISliderService sliderService,
            IMapper mapper)
        {
            _sliderService = sliderService;
            _mapper = mapper;
        }
        [HttpGet]
        public  IViewComponentResult Invoke()
        {
            var slider = _sliderService.GetSliderByType(Core.Enums.SliderTypes.AdvertisingSlider).FirstOrDefault();
            var model = _mapper.Map<SliderModel>(slider);
            return View(model);
        }
    }
}

Presentation/Views/Home/About.cshtml
@model Shop.Services.Dto.Setting.WebsiteSettingModel
@{
    ViewData["Title"] = "درباره ما";
}

<!--about-->
<div class="container-fluid site-logo">
    @*<div class="row col-12 justify-content-center">
            <img class="img-fluid" width="150" src="~/images/logoBig.png" alt="@T["layout-title"].Value" />
        </div>*@
    <div class="row col-12 mt-5 mb-5">
        <!--leyloun-->
        @*<p class="text-justify text-center">
                زندگی ماشینی، تکنولوژی، سرعت در شهرها، این مفهوم ها به خوردن و آشامیدن مان هم راه یافته اند و وزن مفهوم «سلامتی» کاهش یافته است. درحال حاضر در کشورهای پیشرفته، برای بیرون آوردن تغذیه، غذاها و مواد غذایی و آشامیدنی از چنگال تکنولوژی، برنامه ریزی های وسیعی انجام می شود تا به وضعیت طبیعی نزدیک تر شوند. از دیرباز این مسئله ذهنم را مشغول کرده بود که برای بالا بردن سلامتی در شرایط زندگی سریع و تکنولوژیک، چگونه می شود برنامه ریزی نمود. از سال 1368 شروه به تحقیقات و کسب تجربه نمودم و امروزه به این نتیجه رسیدم که بدون وقت گذاشتن، اهمیت دادن، و برنامه ریزی برای سلامتی، تقریبا نمی شود «غذا و نوشیدنی سالم» میل کرد.
            </p>
            <p class="text-justify text-center">
                علاوه بر شرایط رشد و پرورش گیاهان و میوه جاتی که مواد غذایی از آن ها تهیه می شوند، این مواد غذایی باید عاری از انواع مواد نگهدارنده و ترکیبات و طعم دهنده های صنعتی باشند. انواع محصولات را به جای ترکیبات صنعتی، میتوان با انواع طعم دهنده های طبیعی تهیه شده از گیاهان و میوه جات طعم دار نمود. فرهنگ سنتی غنی ما و سایر کشورها حامل بسیاری از خلاقیت ها و روش های کاملا طبیعی است که می توانیم برای برنامه ریزی سلامت غذایی مان از آن ها کمک بگیریم. گردآوری و عرضه این روش ها در برنامه ریزی غذایی هموطنان عزیز، همواره آرزوی من بوده است.امیدواریم مجموعه تلاش هایمان برای تحقیقات و طراحی مواد غذایی، گام مفیدی باشد برای «برنامه ریزی سلامتی غذا»ی شما دوستداران سلامتی.
            </p>*@
        <!--leyloun-->
        @if (Model != null && !String.IsNullOrEmpty(Model.AboutUs))
        {
            <p>@Html.Raw(Model.AboutUs)</p>
        }
    </div>
</div>
<!--about-->

Presentation/Views/Home/ContactUs.cshtml
@using Shop.Core.Domain.Shop
@using System.Text.RegularExpressions;
@model Shop.Models.Message.MessageModel
@{
    ViewData["Title"] = "تماس با ما";
}
<!--Neshan Css-->
<link href="https://static.neshan.org/sdk/leaflet/1.4.0/leaflet.css" rel="stylesheet" type="text/css">
<link href="~/libs/leafLet/css/leaflet-routing-machine.css" rel="stylesheet" />
<link href="~/libs/leafLet/css/leaflet.draw.css" rel="stylesheet" />
<link href="~/libs/leafLet/css/leaflet.awesome-markers.css" rel="stylesheet" />
<!--Neshan Css-->

<div class=" contact-us-section">
    <div class="container">
        <div class="row col-12 p-0 m-0 justify-content-center">
            <div class="col-7">
                <div class="row col-12">
                    <div class="col-12 p-0 m-0 contact-form">
                        <form id="contact-form" method="post" asp-controller="Home" asp-action="ContactUs">
                            <div class="row col-12">
                                <div class="col-6 form-group">
                                    <input asp-for="FullName" class="form-control" placeholder="نام و نام خانوادگی" />
                                    <span asp-validation-for="FullName" class="nikan-val-msg text-danger"></span>
                                </div>
                                <div class="col-6 form-group">
                                    <input asp-for="Email" class="form-control" placeholder="ایمیل" />
                                    <span asp-validation-for="Email" class="nikan-val-msg text-danger"></span>
                                </div>
                            </div>
                            <div class="row col-12">
                                <div class="col-6 form-group">
                                    <input asp-for="Phone" class="form-control" placeholder="همراه" />
                                    <span asp-validation-for="Phone" class="nikan-val-msg text-danger"></span>
                                </div>

                                <div class="col-6 form-group">
                                    <input asp-for="Subject" class="form-control" placeholder="عنوان" />
                                    <span asp-validation-for="Subject" class="nikan-val-msg text-danger"></span>
                                </div>
                            </div>
                            <div class="row col-12">
                                <div class="col-12 form-group">
                                    <textarea asp-for="Description" rows="8" class="form-control" placeholder="توضیحات"></textarea>
                                    <span asp-validation-for="Description" class="nikan-val-msg text-danger"></span>
                                </div>
                            </div>
                            <div class="row col-12 justify-content-center">
                                <div class="col-12 form-group">
                                    <button id="btn-contact" type="submit" class="btn btn-block btn-primary">ارسال</button>
                                </div>
                            </div>

                        </form>
                    </div>
                </div>
            </div>
            <div class="col-5">
                <div class="row col-12">
                    @if (!String.IsNullOrEmpty(ViewBag.ShopAddress))
                    {
                        <div class="col-12">
                            <p>آدرس:</p>
                            <p>@ViewBag.ShopAddress</p>
                        </div>
                    }
                    @if (!String.IsNullOrEmpty(ViewBag.Phones))
                    {
                        string[] phones = Regex.Split(ViewBag.Phones, @"\r?\n|\r");
                        <div class="col-12">
                            <p>شماره تماس:</p>
                            @foreach (var item in phones)
                            {
                                <p>@item</p>
                            }
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>

@if (ViewBag.error != null)
{
    <div style="z-index:9999999999999999" class="text-center offset-3 col-6 alert alert-warning alert-dismissible fade show fixed-top" role="alert">
        <h6 class="text-dark text-center">@ViewBag.error</h6>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
}
@if (ViewBag.success != null)
{
    <div style="z-index:9999999999999999" class="text-center offset-3 col-6 alert alert-success alert-dismissible fade show fixed-top" role="alert">
        <h6 class="text-dark text-center">@ViewBag.success</h6>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
}

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    <script>
        $(document).ready(function () {

            $(".alert").fadeOut(6000);

        });
    </script>

    @*<script src="https://static.neshan.org/sdk/leaflet/1.4.0/leaflet.js" type="text/javascript"></script>
        <script src="~/libs/leafLet/js/leaflet-routing-machine.min.js"></script>
        <script src="~/libs/leafLet/js/L.Polyline.SnakeAnim.js"></script>
        <script src="~/libs/leafLet/js/route.js"></script>
        <script src="~/libs/leafLet/js/leaflet.draw.js"></script>
        <script src="~/libs/leafLet/js/leaflet.awesome-markers.min.js"></script>
        <script src="~/libs/leafLet/js/leaflet.textpath.js"></script>
        <script>
            var map = new L.Map('map', {
                key: 'web.dTOx3dJPU7jOcHICsuQqIFvt5sjLZL6dEUKI8uy3',
                maptype: 'dreamy',
                poi: true,
                traffic: true,
                center: [29.6163064, 52.5013497],
                zoom: 15,
                drawControl: false
            });
            var marker = L.marker([29.6163064, 52.5013497]).addTo(map).bindTooltip("دفتر شیراز",
                {
                    permanent: true,
                    direction: 'auto',
                    sticky: true,
                    className: 'tooltip'
                });

            var teharnmap = new L.Map('teharnmap', {
                key: 'web.dTOx3dJPU7jOcHICsuQqIFvt5sjLZL6dEUKI8uy3',
                maptype: 'dreamy',
                poi: true,
                traffic: true,
                center: [35.741060, 51.300584],
                zoom: 15,
                drawControl: false
            });
            var tehmarker = L.marker([35.741060, 51.300584]).addTo(teharnmap).bindTooltip("دفتر تهران",
                {
                    permanent: true,
                    direction: 'auto',
                    sticky: true,
                    className: 'tooltip'
                });
        </script>*@
}

Presentation/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "صفحه اصلی";
}

@await Component.InvokeAsync("Carousel")
<!-- for leyloun -->
@*@await Component.InvokeAsync("LeylounIndex")*@
<!-- for leyloun -->


@await Component.InvokeAsync("ProductGalleryResource", ResourceTypes.New)
@await Component.InvokeAsync("ProductGalleryResource", ResourceTypes.Special)
@await Component.InvokeAsync("SliderRighLeft")
@await Component.InvokeAsync("ProductGalleryResource", ResourceTypes.BestSellersCount)
@await Component.InvokeAsync("ProductGalleryResource", ResourceTypes.BestSellersPrice)
@await Component.InvokeAsync("SliderAdv")

@if (User.Identity.IsAuthenticated && User.IsInRole(UserRoleNames.User))
{
    @await Component.InvokeAsync("ProductGalleryResource", ResourceTypes.LastVisit)
}

@await Component.InvokeAsync("MainCategory")
@await Component.InvokeAsync("Brands")

<!--StarLand-->
@*<div class="container-fluid p-0 starland-landing">
        <img class="img-fluid" src="~/images//STARLAND.jpg" alt="استارلند" />
    </div>*@
<!--StarLand-->

@section Scripts{
    <script>
        $(document).ready(function () {

               $(".owl-brand ").owlCarousel({
                animateOut: 'zoomOut',
                animateIn: 'zoomIn',
                rtl: true,
                center: false,
                loop: false,
                margin: 10,
                nav: true,
                autoplay: true,
                dots: true,
                autoplayTimeout: 5000,
                autoplayHoverPause: true,
                responsive: {
                    0: {
                        items: 1
                    },
                    600: {
                        items: 3
                    },
                    700: {
                        items: 4
                    },
                    800: {
                        items: 4
                    },
                    1000: {
                        items: 4
                    },
                    1350: {
                        items: 5
                    },
                     1500: {
                        items: 6
                    },
                    2000: {
                        items:8
                    }
                }
                 });
            $(".owl-main-cat ").owlCarousel({
                animateOut: 'zoomOut',
                animateIn: 'zoomIn',
                rtl: true,
                center: false,
                loop: false,
                margin: 10,
                nav: true,
                autoplay: true,
                dots: true,
                autoplayTimeout: 5000,
                autoplayHoverPause: true,
                responsive: {
                    0: {
                        items: 1
                    },
                    600: {
                        items: 3
                    },
                    700: {
                        items: 4
                    },
                    800: {
                        items: 4
                    },
                    1000: {
                        items: 6
                    },
                    1350: {
                        items: 6
                    },
                     1500: {
                        items: 8
                    },
                    2000: {
                        items:10
                    }
                }
                 });

            $(".owl-carousel").owlCarousel({
                animateOut: 'zoomOut',
                animateIn: 'zoomIn',
                rtl: true,
                center: false,
                loop: false,
                margin: 10,
                nav: true,
                autoplay: true,
                dots: true,
                autoplayTimeout: 5000,
                autoplayHoverPause: true,
                responsive: {
                    0: {
                        items: 1
                    },
                    600: {
                        items: 2
                    },
                    700: {
                        items: 2
                    },
                    800: {
                        items: 3
                    },
                    1000: {
                        items: 4
                    },
                    1350: {
                        items: 4
                    },
                     1500: {
                        items: 5
                    },
                    2000: {
                        items:8
                    }
                }
            });      
        });
    </script>
}

Presentation/Views/Home/MellatPayment.cshtml
@model Shop.Services.Dto.Getway.MellatPaymentResult
@{
    ViewData["Title"] = "پرداخت آنلاین";
}
<div class="container text-center">
    @if (Model.IsSuccess)
    {
        <h6 class="alert alert-success text-center">@Model.Message</h6>
        <h6 class="text-center">کد پیگیری:@Model.TransactionNumber</h6>
        <h6 class="text-center">کد مرجع:@Model.RefNumber</h6>
    }
    @if (!Model.IsSuccess)
    {
        <h6 class="alert alert-danger text-center">@Model.Message</h6>
    }
</div>

Presentation/Views/Home/OnlinePayment.cshtml
@model Shop.Services.Dto.Getway.ZarinPalResult
@{
    ViewData["Title"] = "پرداخت آنلاین";
}
<div class="container text-center">
    @if (Model.IsSuccess)
    {
        <h6 class="alert alert-success text-center">@Model.Message</h6>
        <h6 class="text-center">کد پیگیری:@Model.TransactionNumber</h6>
        <h6 class="text-center">کد مرجع:@Model.RefNumber</h6>
    }
    @if (!Model.IsSuccess)
    {
        <h6 class="alert alert-danger text-center">@Model.Message</h6>
    }
</div>